### PR TITLE
Remove the web-console gem

### PR DESCRIPTION
**Pull request by mattreduce**
See the "Rails Webconsole DNS Rebinding issue" email thread for details, also:

https://benmmurphy.github.io/blog/2016/07/11/rails-webconsole-dns-rebinding/

Please update [this spreadsheet](https://docs.google.com/spreadsheets/d/1omuPIH1Nuzmch1WIjVj_VdnB3ERFJxaxe6915sZHAOY/edit) when this has been merged. Thank you! :smile: 

@raulb @heroku/prodsec

### CODE REVIEW

**Comment by raulb** [comment]
@mattreduce not sure if this is still in use or needed. I would suggest following up with the @heroku/build-and-languages team.

**Comment by schneems** [comment]
We don't explicitly use it in any of our examples, however it is used by default when you generate a new rails app

```
$ rails -v 
Rails 5.0.0.1
$ rails new foo
$ cd foo
$ cat Gemfile.lock | grep console
    web-console (3.3.1)
  web-console
```

**Comment by mattreduce** [comment]
@schneems right on. Am I/are we good to merge this and chuck `web-console`?

**Comment by schneems** [comment]
Sure.

**Comment by mattreduce** [comment]
@schneems thanks! :tada:

**Comment by hone** [comment]
@mattreduce +1, we should probably point this to the [devcenter page](https://devcenter.heroku.com/categories/ruby). This hasn't been updated in a year.

**Pull request merged**
